### ISSUE TITLE
ECMA262 Integrity Level

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2340]
**Describe the issue**

There is a broken link

```html
<p><a href="http://www.ecma-international.org/ecma-262/#sec-setintegritylevel">
SetIntegrityLevel</a>(<var>parameter</var>, frozen)</p>
```

It seems to be a faulty redirect on the ecma website, because

https://tc39.es/ecma262/#sec-setintegritylevel

works just fine.

(Fixed in the Proposed Rec)

**Comment by svgeesus** [comment]
Related, these three broken links


    http://www.ecma-international.org/ecma-262/6.0/#sec-get-o-p (lines 13464, 13470)
    http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-data-types-and-values (line 13467)
    http://www.ecma-international.org/ecma-262/6.0/#sec-isconstructor (line 13462)

are fixed by 


    https://tc39.es/ecma262#sec-get-o-p (lines 13464, 13470)
    https://tc39.es/ecma262#sec-ecmascript-data-types-and-values (line 13467)
    https://tc39.es/ecma262#sec-isconstructor (line 13462)

**Comment by rtoy** [comment]
Oh. I didn't fix the other links mentioned in https://github.com/WebAudio/web-audio-api/issues/2340#issuecomment-832723050.  At least not explicitly.

**Comment by rtoy** [comment]
Those still exist.  Re-opening so these links can be fixed.
